Models/DriverViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CodeZen_SDTP.Models
{
    public class DriverViewModel
    {
        [Required(ErrorMessage = "Please Enter Your Name!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter Your Email!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Your Password!")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please Enter Your Mobile Number!")]
        public string Mobile_Number { get; set; }
        [Required(ErrorMessage = "Please Enter Your NIC!")]
        public string NIC { get; set; }
        [Required(ErrorMessage = "Please Enter Your License Number!")]
        public string License_Number { get; set; }

        public int Driver_ID { get; set; }
        public int Vehicle_ID { get; set; }

        public int Insurance_ID { get; set; }
    }
}

Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CodeZen_SDTP.Data;
using CodeZen_SDTP.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace CodeZen_SDTP.Controllers
{
    public class DriverController : Controller
    {
        private readonly IConfiguration _configuration;

        public DriverController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }

        public int getUserID()
        {
            string key = "UserID";
            string CookieValue = Request.Cookies[key];
            int uid;
            int.TryParse(CookieValue, out uid);
            return uid;
        }

        public int uid;

        // GET: DriverVehicles
        public IActionResult Index()
        {
            uid = getUserID();
            DataTable dtbl = new DataTable();
            DataSet dst = new DataSet();
            using (SqlConnection sqlcon = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlcon.Open();
                SqlCommand cmd = new SqlCommand("VehicleViewByID", sqlcon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@User_ID", uid);
                SqlDataReader sdr = cmd.ExecuteReader();
                //SqlDataAdapter sqlDA = new SqlDataAdapter(cmd);
                //sqlDA.Fill(dst);
                dtbl.Load(sdr);

            }
            return View(dtbl);
        }

        // GET: Driver/AddOrEdit/
        public IActionResult AddOrEdit(int uid)
        {
            DriverViewModel driverViewModel = new DriverViewModel();
            if (uid > 0)
            {
                driverViewModel = FetchDriverByID(uid);
            }
            return View(driverViewModel);
        }

        public IActionResult VehicleAdd()
        {
            VehicleViewModel vehicleViewModel = new VehicleViewModel();
            return View(vehicleViewModel);
        }

        //POST: Driver/VehicleAdd
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult VehicleAdd(string Vehicle_RegNo, string VehicleType, int InsuranceCompany)
        {
            uid = getUserID();
            using (SqlConnection sqlcon = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlcon.Open();
                SqlCommand cmd = new SqlCommand("VehicleAddOrEdit", sqlcon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Vehicle_Reg_No", Vehicle_RegNo);
                cmd.Parameters.AddWithValue("@Vehicle_Type", VehicleType);
                cmd.Parameters.AddWithValue("@Insurance_ID", InsuranceCompany);
                cmd.Parameters.AddWithValue("@Driver_ID", uid);
                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }

        // GET: Driver/VehicleAddOrEdit
        public IActionResult VehicleAddOrEdit()
        {
            VehicleViewModel vehicleViewModel = new VehicleViewModel();
            return View(vehicleViewModel);
        }

        //POST: Driver/VehicleAddOrEdit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult VehicleAddOrEdit(string Vehicle_RegNo, int InsuranceCompany)
        {
            uid = getUserID();
            DataTable dtbl = new DataTable();
            DataSet dst = new DataSet();
            using (SqlConnection sqlcon = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlcon.Open();
                SqlCommand cmd = new SqlCommand("VehicleUpdate", sqlcon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@VehicleRegNo", Vehicle_RegNo);
                cmd.Parameters.AddWithValue("@InsuranceID", InsuranceCompany);
                cmd.Parameters.AddWithValue("@DriverID", uid);
                SqlDataReader sdr = cmd.ExecuteReader();
                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }

        public IActionResult VehicleDelete()
        {

            return View();
        }

        [HttpPost]
        public IActionResult VehicleDelete(string Vehicle_RegNo)
        {
            uid = getUserID();
            using (SqlConnection sqlcon = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlcon.Open();
                SqlCommand cmd = new SqlCommand("VehicleDelete", sqlcon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@VehicleRegNo", Vehicle_RegNo);
                cmd.Parameters.AddWithValue("@DriverID", uid);
                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }

        public IActionResult AccidentAddOrEdit()
        {
            return View();
        }

        public IActionResult AccidentDelete()
        {
            return View();
        }

        // POST: Driver/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult AddOrEdit([Bind("Name,Email,Password,Mobile_Number,NIC,License_Number")] DriverViewModel driverViewModel)
        {
            if (ModelState.IsValid)
            {
                using (SqlConnection sqlcon = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
                {
                    sqlcon.Open();
                    SqlCommand sqlcmd = new SqlCommand("DriverAddOrEdit", sqlcon);
                    sqlcmd.CommandType = CommandType.StoredProcedure;
                    sqlcmd.Parameters.AddWithValue("Name", driverViewModel.Name);
                    sqlcmd.Parameters.AddWithValue("Email", driverViewModel.Email);
                    sqlcmd.Parameters.AddWithValue("Password", driverViewModel.Password);
                    sqlcmd.Parameters.AddWithValue("Mobile_Number", driverViewModel.Mobile_Number);
                    sqlcmd.Parameters.AddWithValue("NIC", driverViewModel.NIC);
                    sqlcmd.Parameters.AddWithValue("License_Number", driverViewModel.License_Number);
                    sqlcmd.ExecuteNonQuery();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(driverViewModel);
        }

        // GET: Driver/Delete/5
        public IActionResult Delete(int? id)
        {
            DriverViewModel driverViewModel = FetchDriverByID(id);
            return View(driverViewModel);
        }

        // POST: Driver/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  IActionResult DeleteConfirmed(int id)
        {
            using (SqlConnection sqlcon = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                sqlcon.Open();
                SqlCommand sqlcmd = new SqlCommand("DriverDeleteByID", sqlcon);
                sqlcmd.CommandType = CommandType.StoredProcedure;
                //sqlcmd.Parameters.AddWithValue("Driver_ID", id);
                sqlcmd.ExecuteNonQuery();
            }
            return RedirectToAction(nameof(Index));
        }

        [NonAction]
        public DriverViewModel FetchDriverByID(int? id)
        {
            DriverViewModel driverViewModel = new DriverViewModel();
            using (SqlConnection sqlcon = new SqlConnection(_configuration.GetConnectionString("DevConnection")))
            {
                DataTable dtbl = new DataTable();
                sqlcon.Open();
                SqlDataAdapter SqlDA = new SqlDataAdapter("DriverViewByID", sqlcon);
                SqlDA.SelectCommand.CommandType = CommandType.StoredProcedure;
                //SqlDA.SelectCommand.Parameters.AddWithValue("Driver_ID", id);
                SqlDA.Fill(dtbl);
                if(dtbl.Rows.Count == 1)
                {
                    //driverViewModel.Driver_ID =Convert.ToInt32(dtbl.Rows[0]["Driver_ID"].ToString());
                    driverViewModel.Name = dtbl.Rows[0]["Name"].ToString();
                    driverViewModel.Email = dtbl.Rows[0]["Email"].ToString();
                    driverViewModel.Password = dtbl.Rows[0]["Password"].ToString();
                    driverViewModel.Mobile_Number = dtbl.Rows[0]["Mobile_Number"].ToString();
                    driverViewModel.NIC = dtbl.Rows[0]["NIC"].ToString();
                    driverViewModel.License_Number = dtbl.Rows[0]["License_Number"].ToString();
                }
                return (driverViewModel);
            }
        }
    }
}

Views/Driver/AccidentAddOrEdit.cshtml
@*Report an Accident*@

<div class="col-md-6">
    <h2>Report an Accident</h2>
    <form asp-action="AccidentAddOrEdit">
        <!-- Full names -->
        <div class="form-outline mb-4">
            <div class="form-outline">
                <input type="text" id="form3Example1" class="form-control" />
                <label class="form-label" for="form3Example1">District</label>
            </div>
        </div>

        <!-- Email input -->
        <div class="form-outline mb-4">
            <input type="date" id="form3Example2" class="form-control" />
            <label class="form-label" for="form3Example2">Date</label>
        </div>

        <!-- License Number input -->
        <div class="form-outline mb-4">
            <input type="time" id="form3Example2" class="form-control" />
            <label class="form-label" for="form3Example2">Time</label>
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
            <input type="password" id="form3Example3" class="form-control" />
            <label class="form-label" for="form3Example3">RDA Validate</label>
        </div>

        <!-- Password Confirm -->
        <div class="form-outline mb-4">
            <input type="password" id="form3Example4" class="form-control" />
            <label class="form-label" for="form3Example4">Police Validate</label>
        </div>

        <div class="form-outline mb-4">
            <input type="password" id="form3Example4" class="form-control" />
            <label class="form-label" for="form3Example4">Insurance Validate</label>
        </div>

        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Report</button>
    </form>
</div>


<div class="col-lg-4">
    <a class="btn btn-primary btn-block" asp-controller="Driver" asp-action="AccidentDelete">Delete Report</a>
</div>

Views/Driver/AddOrEdit.cshtml
@model CodeZen_SDTP.Models.DriverViewModel
@* @{
        ViewData["Title"] = Model.Driver_ID == 0 ? "Register" : "Edit Profile";
    } *@

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddOrEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <input type="hidden" asp-for="Driver_ID" />*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile_Number" class="control-label"></label>
                <input asp-for="Mobile_Number" class="form-control" />
                <span asp-validation-for="Mobile_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NIC" class="control-label"></label>
                <input asp-for="NIC" class="form-control" />
                <span asp-validation-for="NIC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="License_Number" class="control-label"></label>
                <input asp-for="License_Number" class="form-control" />
                <span asp-validation-for="License_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<br />

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <h2>Add a Vehicle</h2>
        </div>

        <div class="col-lg-4">
            <a class="btn btn-primary btn-block" asp-controller="Driver" asp-action="VehicleAddOrEdit">Proceed</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Driver/Delete.cshtml
@model CodeZen_SDTP.Models.DriverViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DriverViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile_Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile_Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.License_Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.License_Number)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @* <input type="hidden" asp-for="Driver_ID" /> *@
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Driver/Index.cshtml
@model System.Data.DataTable

@{
    ViewData["Title"] = "List of Drivers";
}

<div class="jumbotron">
    <h1 class="text-center">@ViewData["Title"]</h1>
</div>

@*Vehicle List*@

<h2>Vehicles</h2>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>
                Vehicle ID
            </th>
            <th>
                Driver ID
            </th>
            <th>
                Insurance ID
            </th>
            <th>
                Vehicle Registration Number
            </th>
            <th>
                Vehicle Type
            </th>
            <th>
                <a asp-action="VehicleAdd">Create New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Rows.Count; i++)
            {
        <tr>
            <td>
                @Model.Rows[i]["Vehicle_ID"]
            </td>
            <td>
                @Model.Rows[i]["Driver_ID"]
            </td>
            <td>
                @Model.Rows[i]["Insurance_ID"]
            </td>
            <td>
                @Model.Rows[i]["Vehicle_Reg_No"]
            </td>
            <td>
                @Model.Rows[i]["Vehicle_Type"]
            </td>
            <td>
                @*<a asp-action="VehicleAddOrEdit" asp-route-id="@Model.Rows[i]["Vehicle_ID"]">Edit</a>*@
                <a asp-action="VehicleDelete" asp-route-id="@Model.Rows[i]["Vehicle_ID"]">Delete</a>
            </td>
        </tr>
            }
    </tbody>
</table>

@*Accidents Add or Edit*@
<h2>Accidents Reported</h2>

@*<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>
                Accident ID
            </th>
            <th>
                Driver ID
            </th>
            <th>
                Vehicle ID
            </th>
            <th>
                District
            </th>
            <th>
                Date
            </th>
            <th>
                Time
            </th>
            <th>
                RDA Validate
            </th>
            <th>
                Police Validate
            </th>
            <th>
                Insurance Validate
            </th>
            <th>
                RDA Validate By
            </th>
            <th>
                Police Validate By
            </th>
            <th>
                <a asp-action="AccidentAddOrEdit">Create New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Rows.Count; i++)
        {
        <tr>
            <td>
                @Model.Rows[i]["Accident_ID"]
            </td>
            <td>
                @Model.Rows[i]["Driver_ID"]
            </td>
            <td>
                @Model.Rows[i]["Vehicle_ID"]
            </td>
            <td>
                @Model.Rows[i]["District"]
            </td>
            <td>
                @Model.Rows[i]["Date"]
            </td>
            <td>
                @Model.Rows[i]["Time"]
            </td>
            <td>
                @Model.Rows[i]["RDA Validate"]
            </td>
            <td>
                @Model.Rows[i]["Police Validate"]
            </td>
            <td>
                @Model.Rows[i]["Insurance Validate"]
            </td>
            <td>
                @Model.Rows[i]["RDA Validate By"]
            </td>
            <td>
                @Model.Rows[i]["Police Validate By"]
            </td>
            <td>
                <a asp-action="AccidentAddOrEdit" asp-route-id="@Model.Rows[i]["Accident_ID"]">Edit</a>
                <a asp-action="AccidentDelete" asp-route-id="@Model.Rows[i]["Accident_ID"]">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>*@

Views/Driver/VehicleAdd.cshtml
@model CodeZen_SDTP.Models.VehicleViewModel

<div class="row">
    <div class="col-md-4">
        <form asp-action="VehicleAdd" method="post">

            @*Vehicle ID*@
            <div class="form-outline mb-4">
                <div class="form-outline">
                    <input type="text" id="form3Example1" class="form-control" name="Vehicle_RegNo" />
                    <label class="form-label" for="form3Example1">Vehicle Registration Number</label>
                </div>
            </div>


            @*Vehicl Type*@
            <div class="form-outline mb-4">
                <label class="visually-hidden" for="inlineFormSelectPref">Vehicle Type</label>
                <select class="select" name="VehicleType">
                    <option value="MotorCycle">Motor Cycle</option>
                    <option value="3Wheeler">3 Wheeler</option>
                    <option value="Car">Car</option>
                    <option value="Van">Van</option>
                </select>
            </div>

            @*Insurance Company*@
            <div class="form-outline mb-4">
                <label class="visually-hidden" for="inlineFormSelectPref">Insurance Company</label>
                <select class="select" name="InsuranceCompany">
                    <option value="1">Ceylon Insurance</option>
                    <option value="2">Right Insurance</option>
                    <option value="3">WeGotIt Insurance</option>
                </select>
            </div>

            @*Submit button*@
            <button type="submit" class="btn btn-primary">Add Vehicle</button>
        </form>
    </div>
</div>

Views/Driver/VehicleAddOrEdit.cshtml
@model CodeZen_SDTP.Models.DriverViewModel

<div class="row">
    <div class="col-md-4">
        @*<form asp-action="AddOrEdit"
            Vehicle Reg Number input
            <div class="form-group">
                <label asp-for="Vehicle_Reg_No" class="control-label"></label>
                <input asp-for="Vehicle_Reg_No" class="form-control" />
                <span asp-validation-for="Vehicle_Reg_No" class="text-danger"></span>
            </div>

             Vehicle Type 
            <div class="form-outline mb-4">
                <label class="visually-hidden" for="inlineFormSelectPref">Vehicle Type</label>
                <select class="select">
                    <option value="1">Motor Cycle</option>
                    <option value="2">3 Wheeler</option>
                    <option value="3">Car</option>
                    <option value="4">Van</option>
                    <option value="5">Truck</option>
                </select>
            </div>

             Submit button 
            <button type="submit" class="btn btn-primary">Add Vehicle</button>
        </form>*@
    </div>
</div>

Views/Driver/VehicleDelete.cshtml
@model CodeZen_SDTP.Models.VehicleViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>

<div class="row">
    <div class="col-md-4">
        <form asp-action="VehicleDelete" method="post">

            @*Vehicle ID*@
            <div class="form-outline mb-4">
                <div class="form-outline">
                    <input type="text" id="form3Example1" class="form-control" name="Vehicle_RegNo" />
                    <label class="form-label" for="form3Example1">Vehicle Registration Number</label>
                </div>
            </div>

           

            @*Submit button*@
            <button type="submit" class="btn btn-danger">Delete Vehicle</button>
        </form>
    </div>
</div>